### ISSUE TITLE
Hook failed: "update-status" error

### ISSUE THREAD

**Issue by kelkawi-a** [canonical/openfga-operator#41]
### Bug Description

When deploying the `openfga-k8s` operator and relating it to the `postgresql-k8s` operator, at some point in time the `openfga-k8s` operator goes into an error state as follows:
```
openfga-k8s/0*                       error        idle   192.168.100.186         hook failed: "update-status"
```

The output from `juju debug-log` is provided below.

I can't be too sure whether this is a pebble issue or a charm issue, but other charms in the same model are not facing the same issue.

### To Reproduce

1. `juju deploy openfga-k8s --channel edge`
2. `juju scale-application openfga-k8s 2`
3. `juju deploy postgresql-k8s --channel 14/stable --revision 159`
4. `juju scale-application postgresql-k8s 2`
5. `juju relate openfga-k8s postgresql-k8s`

The error might take a while to happen, but eventually it does.

### Environment

The charm is running on a staging model in PS6 using the `latest/edge` channel and latest revision (18)

### Relevant log output

```shell
unit-openfga-k8s-1: 12:50:46 ERROR unit.openfga-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/./src/charm.py", line 625, in <module>
    main(OpenFGAOperatorCharm)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/main.py", line 456, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/./src/charm.py", line 211, in _on_update_status
    self._ready()
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/./src/charm.py", line 448, in _ready
    if self._migration_is_needed():
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/./src/charm.py", line 424, in _migration_is_needed
    return getattr(self._state, key, None) != self.openfga.get_version()
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/src/openfga.py", line 39, in get_version
    _, stderr = self._run_cmd(cmd)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/src/openfga.py", line 84, in _run_cmd
    process = self.container.exec(cmd, stdin=input_, environment=environment, timeout=timeout)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/model.py", line 2719, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/pebble.py", line 2600, in exec
    resp = self._request('POST', '/v1/exec', body=body)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/pebble.py", line 1754, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-openfga-k8s-1/charm/venv/ops/pebble.py", line 1803, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/openfga/pebble.socket' (container restarted?)
unit-openfga-k8s-0: 12:52:46 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by kelkawi-a** [comment]
My initial investigation into the issue has brought me here:

`charm.py`:
```python
    def _ready(self) -> bool:
        if not self._state.is_ready():
            return False

        if self._migration_is_needed():
            self.unit.status = BlockedStatus("Please run schema-upgrade action")
            return False

        if not self._container.can_connect():
            logger.debug("cannot connect to workload container")
            self.unit.status = WaitingStatus("waiting for the OpenFGA workload")
            return False
```

The error is happening when calling `self._migration_is_needed()`, which seems to be facing issues connecting to the container. I believe performing the `self._container.can_connect()` check first might resolve this issue. I'd be happy to submit a PR with this fix.

The modification would look like this:

```python
    def _ready(self) -> bool:
        if not self._state.is_ready():
            return False

        if not self._container.can_connect():
            logger.debug("cannot connect to workload container")
            self.unit.status = WaitingStatus("waiting for the OpenFGA workload")
            return False

        if self._migration_is_needed():
            self.unit.status = BlockedStatus("Please run schema-upgrade action")
            return False
```
